# Declare ignored files that should be included in deployment:
[deploy]
include = [
  "config/production.yaml",
  "frontend/dist/*",
  "assets/*",
  "frontend/.env"
]

[build]
assets = [
  "config/production.yaml",
  "frontend/dist/*",
  "assets/*",
  "frontend/.env"
]