# Declare ignored files that should be included in deployment:
[deploy]
include = [
  "config/production.yaml",
  "frontend/dist/*",
  "assets/*"
]

[build]
assets = [
  "config/production.yaml",
  "frontend/dist/*",
  "assets/*"
]