//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "player_elo")]
pub struct Model {
    #[sea_orm(column_name = "entryID", primary_key)]
    pub entry_id: i32,
    pub match_id: Option<i64>,
    pub player_name: Option<String>,
    pub player_elos: Option<i32>,
    pub discord_id: Option<i64>,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
